version: '3'
services:
  zk-applepsi:
    platform: linux/amd64
    container_name: zk-applepsi
    image: hicsail/zk-applepsi:main
    volumes:
      - ./src/zk-applepsi:/code/zk-applepsi

  zk-copyright:
    platform: linux/amd64
    container_name: zk-copyright
    image: hicsail/zk-copyright:main
    volumes:
      - ./src/zk-copyright:/code/zk-copyright

  zk-dp:
    platform: linux/amd64
    container_name: zk-dp
    image: hicsail/zk-dp:main
    volumes:
      - ./src/zk-DP:/code/zk-DP
